### PR TITLE
Build with VS2017

### PR DESCRIPTION
**Pull request by acasta69**
Hi, deps updated to VS2017 build.

### CODE REVIEW

**Comment by Dade916** [comment]
The compilation fails because it says libtiff has been compiled with an older version of the compiler.

Does it works for you ?

**Comment by Dade916** [comment]
The full error:

> LINK : fatal error C1047: The object or library file 'E:\projects\luxcorerender\WindowsCompileDeps\x64\Release
>        \lib\libtiff.lib' was created with an older compiler than other objects; rebuild old objects and libraries [E:\projects\luxcorerender\WindowsCompile\Build_CMake\LuxCore\samples\luxcoreui\luxcoreui.vcxproj]

**Comment by acasta69** [comment]
Everything was working fine, but I'm going to check again.

**Comment by Dade916** [comment]
You may have forgot to commit the new libtiff.lib binary.

**Comment by acasta69** [comment]
The problem does not show up here, it builds fine using official repos.
Apparently the libtiff.lib was updated correctly:
old file size was 2676344 bytes, new one is 6226540 bytes (no idea why such a huge difference).

Is it possible that for some reason you have retained the old binary?

**Comment by acasta69** [comment]
According to MS documentation:

> The object or library file 'file' was created with an older compiler than other objects; rebuild old objects and libraries

> C1047 is caused when object files or libraries built with /LTCG are linked together, but where those object files or libraries are built with different versions of the Visual C++ toolset.

> This can happen if you begin using a new version of the compiler but do not do a clean rebuild of existing object files or libraries. 

I have rebuilt that library, to double check the used toolset, but it should be ok.
I am wondering if this may be caused by some odd compiler version incompatibility. I am using version 19.13.26131.1 for x64.

**Comment by Dade916** [comment]
Isn't better just remove the usage of "/LTCG" ? It is the most annoying feature in the universe ! It sooooo slow.

Would it solve all this different version mess ?

I'm on linux at the moment, going to double check if I did a clean compilation as soon as I switch to a Windows PC.

**Comment by acasta69** [comment]
OK, I'll try to build libtiff without /LTCG as soon as possible.

**Comment by acasta69** [comment]
Could you please check if this work? It is still built with /LTCG, but with a slightly more recent compiler version than the one I committed.
[libtiff_19.13.26131.zip](https://github.com/LuxCoreRender/WindowsCompileDeps/files/1985483/libtiff_19.13.26131.zip)

**Comment by Dade916** [comment]
My VS 2017 command line says:

> **********************************************************************
> ** Visual Studio 2017 Developer Command Prompt v15.7.0
> ** Copyright (c) 2017 Microsoft Corporation
> **********************************************************************

A "Check updates" says I have the latest version. And my "About" dialog says:

```
Microsoft Visual Studio Community 2017 
Version 15.7.0
VisualStudio.15.Release/15.7.0+27703.1
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Community

Visual C++ 2017   00369-60000-00001-AA243
Microsoft Visual C++ 2017

ASP.NET and Web Tools 2017   15.0.40501.0
ASP.NET and Web Tools 2017

Azure App Service Tools v3.0.0   15.0.40424.0
Azure App Service Tools v3.0.0

C# Tools   2.8.0-beta6-62830-08. Commit Hash: e595ee276d14e14bfb3eb323fb57f2aa668bddea
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   15.7.18116.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

JavaScript Language Service   2.0
JavaScript Language Service

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.10420.2

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   15.7.18116.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Django support   15.7.18116.1
Provides templates and integration for the Django web framework.

Python - IronPython support   15.7.18116.1
Provides templates and integration for IronPython-based projects.

Python - Profiling support   15.7.18116.1
Profiling support for Python projects.

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   15.7.20419.2003
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.8.0-beta6-62830-08. Commit Hash: e595ee276d14e14bfb3eb323fb57f2aa668bddea
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Windows Machine Learning Generator Extension   1.0
Windows Machine Learning Visual Studio Extension Detailed Info
```

I started with a brand new WindowsDeps clone but I have the same error.

Now going to try your new libtiff_19.13.26131.zip

**Comment by Dade916** [comment]
Nope, same error.

**Comment by Dade916** [comment]
cmake writes this about the found compiler:

`-- The CXX compiler identification is MSVC 19.14.26428.1`

You seem to have an older compile than mine (?).

**Comment by Dade916** [comment]
Some more detail:

```
-- CMake version 3.10.2 detected
-- Selecting Windows SDK version 10.0.17134.0 to target Windows 10.0.16299.
-- The C compiler identification is MSVC 19.14.26428.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.14.26428/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.14.26428/bin/Hostx86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- The CXX compiler identification is MSVC 19.14.26428.1
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.14.26428/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.14.26428/bin/Hostx86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Multi-config generator detected
-- MSVC
-- MSVC Version: 1914
-- Using default WIN32 Configuration settings
-- Building for target x86
```

**Comment by acasta69** [comment]
Microsoft is updating VS2017 quite frequently... I have two slightly different versions on different machines, and you have one even more recent. I hope this will not cause too many problems.
Here you can find libtiff and its dependencies built without LTCG. If they work for you, I'll send a new pull request.
Let's hope no other deps will show this problem.
[lib_no_LTCG.zip](https://github.com/LuxCoreRender/WindowsCompileDeps/files/1987331/lib_no_LTCG.zip)

**Comment by acasta69** [comment]
In the meantime I have updated to your same VS version and now I have the problem on another library.
I'm going to remove LTCG from all dependencies and issue a new pull request.

**Comment by Dade916** [comment]
Ok, thanks Alessandro. Yes, LTCG is very annoying and it can be a source of endless problems for anyone with a slighter different version of the compiler.

**Pull request merged**
